[package]
name = "scan"
version = "3.3.0-rc.2"
edition = "2024"

[profile.release]
strip = true # Automatically strip symbols from the binary
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "2.0"
ipnet = "2.12"
main_error = "0.1.2"
clap = { version = "4.6", features = ["derive"] }
tokio = { version = "1.53", features = ["full"] }
ping = { version = "0.9.0", features = ["tokio"] }

[lints.clippy]
# UM, ACTUALLY
pedantic = { level = "warn", priority = -1 }
# DEVELOPING LINTS
nursery = { level = "warn", priority = -1 }
# DENY PANICS
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
